engines:
  rubocop:
    enabled: true
    #checks:
    # Rubocop/Metrics/ClassLength:
    #   enabled: false
  brakeman:
    enabled: true
    #exclude_fingerprints:
    #- 08c185b3f764f262539a1f76997d3a89
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
        #mass_threshold: 30
ratings:
  paths:
  - app/**
  - "**.rb"
exclude_paths:
- spec/**/*
- app/assets/javascripts/jquery.min.js
- app/assets/javascripts/jquery.scrollex.js
- app/assets/javascripts/jquery.scrolly.js
- app/assets/javascripts/main.js
- app/assets/javascripts/paper-full.js
- app/assets/javascripts/skel.min.js
- app/assets/javascripts/util.js
